"""
pythoneda/realm/rydnr/application/rydnr_app.py

This file can be used to run Rydnr's PythonEDA realm.

Copyright (C) 2023-today rydnr's pythoneda-realm-rydnr/application

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
import asyncio
from pythoneda.application import PythonEDA

class RydnrApp(PythonEDA):
    """
    Runs the Rydnr's PythonEDA realm.

    Class name: RydnrApp

    Responsibilities:
        - Runs the Rydnr's PythonEDA realm.

    Collaborators:
        - Command-line handlers from pythoneda-realm-rydnr/infrastructure
    """
    def __init__(self):
        """
        Creates a new Rydnr instance.
        """
        # rydnr_banner is automatically generated by pythoneda-realm-rydnr/application-artifact
        banner = None
        try:
            from pythoneda.realm.rydnr.application.rydnr_banner import RydnrBanner
            banner = RydnrBanner()
        except ImportError:
            pass
        from pythoneda.realm.rydnr.rydnr import Rydnr
        super().__init__(banner, __file__)

if __name__ == "__main__":
    asyncio.run(RydnrApp.main("pythoneda.realm.rydnr.Rydnr"))
